### ISSUE TITLE
create automated builds off hub.docker.com or quay.io

### ISSUE THREAD

**Issue by bacongobbler** [jumbojett/deis-ui#11]
Setting up an automated build allows users to pull the latest image of deis-ui from master (latest) or from a tag without relying on us or CI to push builds. We can do this using one of two ways:
1. Create a user on DockerHub, then create a repository for deis-ui. Once that's set up, create a hook that will build a Docker image on every push. [link to the docs](https://docs.docker.com/docker-hub/builds/)
2. Same thing as above, but for quay.io. [link](http://blog.devtable.com/2014/03/link-your-quayio-repositories-to-github.html)

**Comment by jumbojett** [comment]
Hi @bacongobbler ! I setup something on DockerHub a while back. Will this suffice? https://hub.docker.com/r/jumbojett/deis-ui/

**Comment by bacongobbler** [comment]
Yep! Thanks :)
