### ISSUE TITLE
Not working with current version of deis

### ISSUE THREAD

**Issue by goranships** [jumbojett/deis-ui#3]
Hello,

I have successfully build and wake up the website, i can login to controller but there is no apps inside!

Can you take a look and solve the problem?

**Comment by Joshua-Anderson** [comment]
If you open up the console you will probably see an error that you aren't allowed to send the authorization header. I fixed this in deis itself and it should work with the next release.

**Comment by olalonde** [comment]
I'm also getting this.

```
Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
(index):1 XMLHttpRequest cannot load http://deis.mydomain.com/v1/apps. Request header field Authorization is not allowed by Access-Control-Allow-Headers.
```

How can I update deis to fix this?

**Comment by bacongobbler** [comment]
@olalonde you can build off master; https://github.com/deis/deis/pull/3253 was merged and will make it into the next release.

**Comment by olalonde** [comment]
Ok thanks;
